### ISSUE TITLE
Mixed Chart Types

### ISSUE THREAD

**Issue by RinoGaetano94** [xdev-software/chartjs-java-model#128]
Support for mixed chart types would be great. 

Here the chart.js documentation: 
https://www.chartjs.org/docs/latest/charts/mixed.html

Thanks!

**Comment by alessandrodibiagio** [comment]
Great library, but it would be fantastic if it handled combo charts like this:

https://www.chartjs.org/docs/latest/samples/other-charts/combo-bar-line.html

Many thanks!

**Comment by AB-xdev** [comment]
Implemented by https://github.com/xdev-software/chartjs-java-model/commit/26f3e1dcffac7221368fb6cd7b39e836f715cd5c
