### ISSUE TITLE
Proposal: Instead of using int, double and BigDecimal, the Number abstract class can be used

### ISSUE THREAD

**Issue by aripddev** [xdev-software/chartjs-java-model#154]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

Advantages are;

1. Instead of using int, double and BigDecimal, you can create shorter classes using the Number abstract class.
2. Sometimes there may be null or Double.NaN values in the data. https://www.chartjs.org/docs/latest/general/data-structures.html#object

Therefore, my suggestion is to create an interface `NumberDataset.java` file instead of [BigDecimalDataset.java](https://github.com/xdev-software/chartjs-java-model/blob/develop/chartjs-java-model/src/main/java/software/xdev/chartjs/model/dataset/BigDecimalDataset.java) file and remove int, double, BigDecimal and use Number abstract class instead. 

As an example, the current `ScatterDataPoint` file;

```java
public class ScatterDataPoint extends XYDataPointBase<ScatterDataPoint>
{
	public ScatterDataPoint()
	{
	}
	
	public ScatterDataPoint(final int x, final int y)
	{
		super(x, y);
	}
	
	public ScatterDataPoint(final double x, final double y)
	{
		super(x, y);
	}
	
	public ScatterDataPoint(final BigDecimal x, final BigDecimal y)
	{
		super(x, y);
	}
}
```

and  after the change

```java
public class ScatterDataPoint extends XYDataPointBase<ScatterDataPoint>
{
	public ScatterDataPoint()
	{
	}
	
	public ScatterDataPoint(final Number x, final Number y)
	{
		super(x, y);
	}
	
}
```

and proposed `NumberDataset.java`

```java
public interface NumberDataset<S extends Dataset<?, Number>>
{
	S self();
	
	default S setData(final Number... data)
	{
		this.self().clearData();
		if(data != null)
		{
			Arrays.stream(data).forEach(this::addData);
		}
		return this.self();
	}
	
	/**
	 * Add the data point to this {@code Dataset}
	 *
	 * @see Dataset#setData(Collection)
	 */
	default S addData(final Number data)
	{
		this.self().addData(data);
		return this.self();
	}
}
```

**Comment by aripddev** [comment]
In a project I'm working on, the following errors are thrown because `null` or `Double.NaN` values are not accepted by the current `BigDecimalDataset`.

For the Double.NaN value;

> Caused by: java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:586)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:471)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:900)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1368)
	at software.xdev.chartjs.model.dataset.BigDecimalDataset.addData(BigDecimalDataset.java:60)

The graphical output I expected;
label: [2026-01-01, 2026-11-26, 2026-11-27, 2027-01-01]
dataset1: [2.8, NaN, NaN, 3.8]
dataset2: [0.0, 0.0, 0.0, 0.1]

<img width="400" alt="Screenshot 2024-05-16 at 21 41 11" src="https://github.com/xdev-software/chartjs-java-model/assets/9448030/a94c0c30-693d-4c0e-b51a-ba98193e1745">

Since I am unable to set null or Double.NaN value, I cannot have the chart that I expected.

**Comment by AB-xdev** [comment]
Thank you for the issue,

This is from the [original implementation](https://github.com/mdewilde/chart/blob/7d896c8c316a3c62bfcd0b75955bf92c559708cf/src/main/java/be/ceau/chart/datapoint/ScatterDataPoint.java#L36-L49) and was never changed.

But I have to agree that this makes a lot of sense. I will do a quick PR
