### ISSUE TITLE
Shortcomings in simplifying the API by using Number instead of BigDecimal

### ISSUE THREAD

**Issue by aripddev** [xdev-software/chartjs-java-model#158]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

Related to #154. I will provide PR.

**Comment by melloware** [comment]
@AB-xdev just wanted to give you a shout out that we have updated the PrimeFaces showcase to use your library and link to it vs our own homegrown classes that were becoming too burdensome to maintain!

Check it out: https://www.primefaces.org/showcase/ui/chart/bar.xhtml

**Comment by melloware** [comment]
weird i am not seeing that?

![image](https://github.com/xdev-software/chartjs-java-model/assets/4399574/5e7f3d33-6e9c-4a8b-a856-1eb9493c5590)

**Comment by AB-xdev** [comment]
> weird i am not seeing that?


```
> curl --head https://www.primefaces.org/showcase/ui/chart/bar.xhtml

HTTP/1.1 302 Found
Date: Mon, 27 May 2024 11:35:34 GMT
Server: Jetty(9.4.36.v20210114)
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: http://www.primefaces.org/showcase/ui/chart/bar.xhtml?jfwid=2f75b
Set-Cookie: pf.initialredirect-2f75b=true; Path=/; Expires=Mon, 27-May-2024 11:36:04 GMT; Max-Age=30
X-Frame-Options: sameorigin
Content-Type: application/xhtml+xml
```

**Comment by melloware** [comment]
Weird what region of the world are you in? I am in Eastern USA so maybe its regioinal?

**Comment by melloware** [comment]
OK let me notify them.

**Comment by aripddev** [comment]
It is the same in here, Istanbul.
