### ISSUE TITLE
Infinite loop in JSON serialization 

### ISSUE THREAD

**Issue by melloware** [xdev-software/chartjs-java-model#174]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/chartjs-java-model/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.4.1

### Steps to reproduce the bug

See https://github.com/orgs/primefaces/discussions/2076

issue reported on PrimeFaces forum with diagnosis and workaround. 

### Expected behavior

No infiniteloop

**Comment by AB-xdev** [comment]
So I checked the mentioned code and uhm it works fine when I execute it inside the demo project...

**Comment by AB-xdev** [comment]
Anyway I added a ``JsonIgnore`` for now, this should in fix the problem in any way

**Comment by melloware** [comment]
Fixed!
