### ISSUE TITLE
The Class "TitlePosition" should add enum LEFT and RIGHT

### ISSUE THREAD

**Issue by dengbingaliyun** [xdev-software/chartjs-java-model#175]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

ChartJs support  chart title on top,bottom,left and right by default . Primefaces can also define the title position of a chart.
Please add those features in further version . 
Thanks

**Comment by AB-xdev** [comment]
I corrected model for Title and Font in 1.5.0 should be fixed there.
