### ISSUE TITLE
Please add the missing attributes in AbstractTickOptions

### ISSUE THREAD

**Issue by dengbingaliyun** [xdev-software/chartjs-java-model#185]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

There are 3 missing attrributes in version 2.0.x .Please update it in the future version.  
```
	protected Object fontColor;
	protected Boolean offset;
	protected Boolean beginAtZero;
```

**Comment by AB-xdev** [comment]
Thank you for the issue.

However these options are not present in the [docs](https://www.chartjs.org/docs/latest/axes/#common-tick-options-to-all-axes) nor inside the [source code](https://github.com/chartjs/Chart.js/blob/v4.4.3/src/types/index.d.ts#L3026).

For example [``beginAtZero`` was renamed when 3.x](https://github.com/chartjs/Chart.js/blob/4ee6c9e279dcb47710001e7d99744f5e6290f250/docs/migration/v3-migration.md?plain=1#L88) was released.

Could you please let me know where you got the information from that they should be inside there?

**Comment by dengbingaliyun** [comment]
I saw your link,  you are right.  I was referenced by pf APIs. Please ignore the "beginAtZero".

**Comment by AB-xdev** [comment]
Okay, I think we can close the issue then or?

**Comment by dengbingaliyun** [comment]
How about fontColor and offset?

**Comment by AB-xdev** [comment]
Neither of them are inside the source code or docs.

* ``fontColor`` was likely renamed to ``color``
* I can't find what ``offset`` is for as it's not present in the ChartJS 2.x docs... maybe it was renamed to ``padding``?

**Comment by dengbingaliyun** [comment]
I've tested color and fontColor ,they are different . The fontColor refer to the color of tick .Please see the picture.
![QQ截图20240614150508](https://github.com/xdev-software/chartjs-java-model/assets/11456193/fe9eda3e-444d-4b35-9acc-7a6f22d4303d)

**Comment by dengbingaliyun** [comment]
Thanks!
