### ISSUE TITLE
Support Mixed Model?

### ISSUE THREAD

**Issue by melloware** [xdev-software/chartjs-java-model#189]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Chart.js supports Mixed Models does XDEV?

Mixed: https://www.chartjs.org/docs/latest/charts/mixed.html 

Original PrimeFaces discussion: https://github.com/orgs/primefaces/discussions/2133

**Comment by aripddev** [comment]
@melloware yes, it is. You can check `software.xdev.chartjs.model.charts.MixedChart` and `software.xdev.chartjs.model.data.MixedData`. I use it in one of our projects.

**Comment by melloware** [comment]
Nice!
