### ISSUE TITLE
Migration from PF 13 to 14 - Handling "no data" 

### ISSUE THREAD

**Issue by uvula** [xdev-software/chartjs-java-model#198]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

I just have a question.
I migrating from Primefaces(PF) 13 to 14. I have some chart and go to XDEV chartjs-java-model.
It is more or less easy to migrate because the *Chart, *Data, *Dataset are similar.
But I didn't have investigated the new library very well yet.

**My question:**
I found: "no data" are not handled by the library itself, with PF lib not a problem seen yet.
I got the "Chart not drawable" exceptions, e.g because I have no data samples from my source.
I handle this now in my code.

But I'd like to have support from chartjs-java-model to generate "empty" charts, so I can handle it easier
in my code.

E.g:

chartJson = ChartUtil.buildGraph(LineChart.class, () -> {
  <code to generate a LineChart, maybe with empty dataset>
  return model.toJson();
});

public static String buildGraph(Class<? extends HomogeneousChart<?,?,?>> clazz, Supplier<String> supplier) {
	Objects.requireNonNull(clazz);
	Objects.requireNonNull(supplier);
	try {
		return supplier.get();
	} catch (Throwable t) {
		if ( !( t instanceof IllegalArgumentException))
			logger.error(t);
		**return  generateEmptyChart(clazz)   // somehow generate easy by chartjs-java-model library** 
	}
}

Does it make sense?

**Comment by AB-xdev** [comment]
Thank you for the issue

I see a few options here:
1. Check inside your code if the data you fetched is empty and if so display another component instead of the chart that e.g. says "No data found" or something. I think this is the best and user friendliest decision.
2. Alternatively you can also use ``toJsonNative`` to bypass the ``isDrawable``-check, however this might result in unexpected drawings
