### ISSUE TITLE
Color: add HSLA support

### ISSUE THREAD

**Issue by jepsar** [xdev-software/chartjs-java-model#238]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

The current color object only supports RGBA. When it comes to generating random colors HSLA is easier to work with (to get colors with a consistent darkness for example).

**Comment by AB-xdev** [comment]
Fixed by https://github.com/xdev-software/chartjs-java-model/commit/3468543b5cf5c1e6d7e22add93a651d8bbc1d8a0

will be released with the next version

**Comment by jepsar** [comment]
That's quick! Thank you!
