### ISSUE TITLE
PointDataset.setPointStyle is missing an option to disable it

### ISSUE THREAD

**Issue by dhelml** [xdev-software/chartjs-java-model#280]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/chartjs-java-model/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.3.1

### Steps to reproduce the bug

1. Check documentation on chartjs.org
2. Check enum PointStyle in chartjs-java-model

### Expected behavior

The documentation on chartjs.org states the following values for Elements => Point Styles:

Info

When a string is provided, the following values are supported:

    'circle'
    'cross'
    'crossRot'
    'dash'
    'line'
    'rect'
    'rectRounded'
    'rectRot'
    'star'
    'triangle'
    false

### Actual behavior

`public enum PointStyle
{
	CIRCLE,
	TRIANGLE,
	RECT,
	RECT_ROUNDED,
	RECT_ROT,
	CROSS,
	CROSS_ROT,
	STAR,
	LINE,
	DASH;
}`

The boolean value "false" is missing

### Additional information

This is the only value that hides the marking. If there is another way within chartjs-java-model, I couldn't find it

**Comment by AB-xdev** [comment]
Thank you for the issue.
I can confirm the problem. Changing the type to a ``Object`` should make it possible to set the value accordingly.

> The documentation on chartjs.org states the following values for Elements => Point Styles

A link would also be nice next time ;)

**Comment by AB-xdev** [comment]
Fix should be available in the next release :)
