### ISSUE TITLE
How can I declare the tooltip to behave like the old X-axis mode?

### ISSUE THREAD

**Issue by dhelml** [xdev-software/chartjs-java-model#281]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Within [chart.js migration guide](https://www.chartjs.org/docs/4.3.0/migration/v3-migration.html#interactions).
They say that they adjusted the mode options. Chartjs-java-model does provide a setHover() and setMode() function but the javadoc does still reference the old values. Since it is only a String parameter I can write the new values, but I can't seem to find an option for intersect.
As stated within the migration guide: modes`['X-axis']` was replaced with `{mode: 'index', intersect: false}`

Is there a way to get that `intersect: false` attribute implicitly?

**Comment by AB-xdev** [comment]
Can confirm the problem, the java class is outdated and still uses the old ChartJS v2 API.

It should probably use 
* https://github.com/chartjs/Chart.js/blob/v4.4.6/src/types/index.d.ts#L1674-L1676
* https://github.com/chartjs/Chart.js/blob/v4.4.6/src/types/index.d.ts#L1564

**Comment by AB-xdev** [comment]
Fixed.

You can now use https://github.com/xdev-software/chartjs-java-model/blob/9c9f41f9e1ef1314e839ffb275659a4d1efd1a7a/chartjs-java-model/src/main/java/software/xdev/chartjs/model/options/CoreInteractionOptions.java (available in the next release)
