### ISSUE TITLE
Allow JavaScriptFunction for GridLaneConfiguration lineWidth

### ISSUE THREAD

**Issue by dhelml** [xdev-software/chartjs-java-model#289]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/chartjs-java-model/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.5.0

### Steps to reproduce the bug

1. Check docu on [chartjs.org](https://github.com/chartjs/Chart.js/blob/47245a7/src/types/index.d.ts#L2993) for GridLineOptions
```
  /**
   * @default 1
   */
  lineWidth: ScriptableAndArray<number, ScriptableScaleContext>;
```
2. Allowed values should be Number and JavaScriptFunction

### Expected behavior

Same options for Java available

### Actual behavior

Only Number supported

### Additional information

GridLaneConfiguration color and tickColor has that usecase allready available.
Same option is also missing for tickBorderDash and tickBorderDashOffset.

**Comment by AB-xdev** [comment]
Will be available in the next release :)
