### ISSUE TITLE
Doughnut and Pie Charts - Config Options incomplete/incorrect

### ISSUE THREAD

**Issue by DazzlingBob** [xdev-software/chartjs-java-model#293]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/chartjs-java-model/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.5.0

### Steps to reproduce the bug

- cutoutPercentage is legacy: Doughnut cutoutPercentage was renamed to cutout and accepts pixels as number and percent as string ending with % (see https://www.chartjs.org/docs/latest/migration/v3-migration.html).
- Can't figure out how to set animation.animateRotate/animation.animateScale

For the latest spec see: https://www.chartjs.org/docs/latest/charts/doughnut.html#config-options

### Expected behavior

example expected api:
```
  PieOptions pieOptions = new PieOptions()
    .setResponsive(true)
    .setMaintainAspectRatio(true)
    .setCutout("50%")
    .setAnimation(new PieAnimation()
      .setAnimateRotate(true)
      .setAnimateScale(false))
    );
```

Generates:
 ```
 "options": {
    "responsive": true,
    "maintainAspectRatio": true,
    "cutout": "50%",
    "animation": {
      "animateRotate": true,
      "animateScale": false
  }
```

### Actual behavior

example current api:

```
  PieOptions pieOptions = new PieOptions()
    .setResponsive(true)
    .setMaintainAspectRatio(true)
    .setCutoutPercentage(50)
    .setAnimations(new Animations<>(AnimationType.X, new PieAnimation()
      .setAnimateRotate(true)
      .setAnimateScale(false))
    );
```

Generates:
```
  "options": {
    "responsive": true,
    "maintainAspectRatio": true,
    "cutoutPercentage": 50,
    "animations":{"animationTypes":{"x":{"animateRotate":true,"animateScale":false}},"x":{"animateRotate":true,"animateScale":false}}  
}

```

**Comment by AB-xdev** [comment]
Should now be up to date with the Chart JS source.
Will be available in the next release :)
