### ISSUE TITLE
Missing support of certain data structures

### ISSUE THREAD

**Issue by Rapster** [xdev-software/chartjs-java-model#48]
Data structures supported in chartjs: https://www.chartjs.org/docs/latest/general/data-structures.html

As of today, only primitives are supported (see `Dataset#data`), would be great to have full support of chartjs data structures (at least to achieve something similar tothis: https://codepen.io/analizapandac/pen/JwrdNW)

**Comment by AB-xdev** [comment]
Okay issue description is a bit odd but I believe you want to set also other objects like than ``BigDecimal`` for ``BarDataset#data`` or?
Formats are specified here: https://www.chartjs.org/docs/latest/general/data-structures.html 

Is this correct?

**Comment by Rapster** [comment]
Correct

**Comment by AB-xdev** [comment]
Released in ``1.1.0``

**Comment by Rapster** [comment]
You rock! Thank you very much
