### ISSUE TITLE
AngelLines: LineWidth should be BigDecimal

### ISSUE THREAD

**Issue by melloware** [xdev-software/chartjs-java-model#76]
Currently `AngleLines.setLineWidth(Integer)`

However it can be a BigDecimal or float  and set with `setLineWidth(0.5f)`

https://www.chartjs.org/docs/latest/axes/radial/linear.html#angle-line-options

**Comment by AB-xdev** [comment]
Fixed by https://github.com/xdev-software/chartjs-java-model/commit/b5743cb95a544dee0fe4b8e7d25be4873a14d396 :)

Release will follow shortly

**Comment by melloware** [comment]
you rock @AB-xdev

**Comment by melloware** [comment]
@AB-xdev as a note I also submitted a PR to have your library listed here: https://github.com/chartjs/awesome/pull/74
