### ISSUE TITLE
Time* axes are not present

### ISSUE THREAD

**Issue by astappiev** [xdev-software/chartjs-java-model#90]
Some classes, e.g. `software.xdev.chartjs.model.options.scales.Time` already exist but are not connected anywhere.
Something like `software.xdev.chartjs.model.options.scales.TimeCartesianScale` is missing.

https://www.chartjs.org/docs/latest/axes/cartesian/time.html

**Comment by AB-xdev** [comment]
Thank you for the PR :)
I guess This should be fixed now.

If not please reopen the issue.
