### ISSUE TITLE
Need a way to disable `isDrawable` check

### ISSUE THREAD

**Issue by astappiev** [xdev-software/chartjs-java-model#91]
I want to create a time series bar chart, however, the `isDrawable` check fails due to `data.labels` missing. I don't need them because my dataset consists of points with time and value. It's rendered fine if I override and hardcode this method to `true`.

**Comment by AB-xdev** [comment]
Thank you for the issue.
This should be fixed with https://github.com/xdev-software/chartjs-java-model/commit/99163aba1f37f947837b5cfa65977da46987e4a3
